"""
Generators — produce Dockerfile, CI/CD pipeline YAML, and Helm chart files
for any service type and tech stack.
"""
from __future__ import annotations
from typing import NamedTuple


class GeneratedFile(NamedTuple):
    path:    str
    content: str


# ── Tech-stack base images ────────────────────────────────────────────────────

_BASE_IMAGES: dict[str, str] = {
    "Node.js":      "node:20-alpine",
    "Python":       "python:3.12-slim",
    "FastAPI":      "python:3.12-slim",
    "Django":       "python:3.12-slim",
    "Go":           "golang:1.22-alpine",
    "Java":         "eclipse-temurin:21-jre-alpine",
    "Spring Boot":  "eclipse-temurin:21-jre-alpine",
    "Rust":         "rust:1.78-alpine",
    "React":        "node:20-alpine",
    "Next.js":      "node:20-alpine",
    "Other":        "ubuntu:22.04",
}

_INSTALL_CMDS: dict[str, str] = {
    "Node.js":      "RUN npm ci --production",
    "Python":       "RUN pip install --no-cache-dir -r requirements.txt",
    "FastAPI":      "RUN pip install --no-cache-dir -r requirements.txt",
    "Django":       "RUN pip install --no-cache-dir -r requirements.txt",
    "Go":           "RUN go build -o /app/server .",
    "Java":         "COPY target/*.jar app.jar",
    "Spring Boot":  "COPY target/*.jar app.jar",
    "Rust":         "RUN cargo build --release",
    "React":        "RUN npm ci && npm run build",
    "Next.js":      "RUN npm ci && npm run build",
    "Other":        "RUN echo 'Add build steps here'",
}

_ENTRYPOINTS: dict[str, list[str]] = {
    "Node.js":      ["node", "src/index.js"],
    "Python":       ["python", "main.py"],
    "FastAPI":      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"],
    "Django":       ["python", "manage.py", "runserver", "0.0.0.0:8080"],
    "Go":           ["/app/server"],
    "Java":         ["java", "-jar", "app.jar"],
    "Spring Boot":  ["java", "-jar", "app.jar"],
    "Rust":         ["./target/release/server"],
    "React":        ["npx", "serve", "-s", "build", "-l", "8080"],
    "Next.js":      ["npm", "start"],
    "Other":        ["sh", "-c", "echo 'Container started'"],
}


# ── Dockerfile generator ──────────────────────────────────────────────────────

def generate_dockerfile(tech_stack: str, service_type: str) -> GeneratedFile:
    base   = _BASE_IMAGES.get(tech_stack, "ubuntu:22.04")
    install = _INSTALL_CMDS.get(tech_stack, "RUN echo 'No build step'")
    ep     = _ENTRYPOINTS.get(tech_stack, ["sh", "-c", "sleep infinity"])
    ep_str = ", ".join(f'"{e}"' for e in ep)

    content = f"""# Auto-generated by UniOps Deployment Engine
# Service Type : {service_type}
# Tech Stack   : {tech_stack}

FROM {base}

WORKDIR /app

# Install dependencies
COPY . .
{install}

# Runtime
EXPOSE 8080
ENTRYPOINT [{ep_str}]
"""
    return GeneratedFile("Dockerfile", content)


# ── GitHub Actions CI/CD generator ────────────────────────────────────────────

def generate_github_actions(service_name: str, tech_stack: str, namespace: str, cluster: str) -> GeneratedFile:
    test_step = ""
    if tech_stack in ("Node.js", "React", "Next.js"):
        test_step = "      - run: npm test --if-present"
    elif tech_stack in ("Python", "FastAPI", "Django"):
        test_step = "      - run: pytest --tb=short || true"
    elif tech_stack == "Go":
        test_step = "      - run: go test ./..."

    content = f"""# Auto-generated by UniOps Deployment Engine
name: CI/CD — {service_name}

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: ${{{{ github.repository_owner }}}}/{service_name}
  NAMESPACE: {namespace}
  CLUSTER: {cluster}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{{{ github.actor }}}}
          password: ${{{{ secrets.GITHUB_TOKEN }}}}

{test_step}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{{{ github.ref == 'refs/heads/main' }}}}
          tags: |
            ghcr.io/${{{{ env.IMAGE_NAME }}}}:latest
            ghcr.io/${{{{ env.IMAGE_NAME }}}}:${{{{ github.sha }}}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Trigger UniOps deployment sync
        run: |
          echo "Deployment triggered for {service_name}"
          echo "Image: ghcr.io/${{{{ env.IMAGE_NAME }}}}:${{{{ github.sha }}}}"
          echo "Target: ${{{{ env.CLUSTER }}}} / ${{{{ env.NAMESPACE }}}}"
"""
    return GeneratedFile(".github/workflows/ci.yml", content)


def generate_gitlab_ci(service_name: str, tech_stack: str, namespace: str) -> GeneratedFile:
    content = f"""# Auto-generated by UniOps Deployment Engine
image: docker:24

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/{service_name}
  NAMESPACE: {namespace}

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest
  only:
    - main
    - develop

deploy:
  stage: deploy
  script:
    - echo "Deploying {service_name} to $NAMESPACE"
    - echo "Image $IMAGE_NAME:$CI_COMMIT_SHA"
  only:
    - main
  environment:
    name: production
"""
    return GeneratedFile(".gitlab-ci.yml", content)


# ── Helm chart generator ──────────────────────────────────────────────────────

def generate_helm_chart(service_name: str, namespace: str, replicas: int, image: str = "") -> list[GeneratedFile]:
    safe_name = service_name.lower().replace("_", "-")
    image     = image or f"ghcr.io/org/{safe_name}:latest"

    chart_yaml = f"""# Auto-generated by UniOps Deployment Engine
apiVersion: v2
name: {safe_name}
description: Helm chart for {safe_name} — managed by UniOps Control Tower
type: application
version: 0.1.0
appVersion: "1.0.0"
"""

    values_yaml = f"""# Auto-generated by UniOps Deployment Engine
replicaCount: {replicas}

image:
  repository: {image.split(':')[0]}
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

nodeSelector: {{}}
tolerations: []
affinity: {{}}
"""

    deployment_yaml = f"""# Auto-generated by UniOps Deployment Engine
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{{{ include "{safe_name}.fullname" . }}}}
  namespace: {namespace}
  labels:
    {{{{- include "{safe_name}.labels" . | nindent 4 }}}}
    app.kubernetes.io/managed-by: uniops
spec:
  replicas: {{{{ .Values.replicaCount }}}}
  selector:
    matchLabels:
      {{{{- include "{safe_name}.selectorLabels" . | nindent 6 }}}}
  template:
    metadata:
      labels:
        {{{{- include "{safe_name}.selectorLabels" . | nindent 8 }}}}
    spec:
      containers:
        - name: {{{{ .Chart.Name }}}}
          image: "{{{{ .Values.image.repository }}}}:{{{{ .Values.image.tag | default .Chart.AppVersion }}}}"
          imagePullPolicy: {{{{ .Values.image.pullPolicy }}}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{{{- toYaml .Values.livenessProbe | nindent 12 }}}}
          readinessProbe:
            {{{{- toYaml .Values.readinessProbe | nindent 12 }}}}
          resources:
            {{{{- toYaml .Values.resources | nindent 12 }}}}
"""

    service_yaml = f"""# Auto-generated by UniOps Deployment Engine
apiVersion: v1
kind: Service
metadata:
  name: {{{{ include "{safe_name}.fullname" . }}}}
  namespace: {namespace}
  labels:
    {{{{- include "{safe_name}.labels" . | nindent 4 }}}}
spec:
  type: {{{{ .Values.service.type }}}}
  ports:
    - port: {{{{ .Values.service.port }}}}
      targetPort: {{{{ .Values.service.targetPort }}}}
      protocol: TCP
      name: http
  selector:
    {{{{- include "{safe_name}.selectorLabels" . | nindent 4 }}}}
"""

    helpers_tpl = f"""{{{{/*
Auto-generated Helm helpers — UniOps Deployment Engine
*/}}}}
{{{{- define "{safe_name}.fullname" -}}}}
{{{{- .Release.Name | trunc 63 | trimSuffix "-" }}}}
{{{{- end }}}}

{{{{- define "{safe_name}.labels" -}}}}
helm.sh/chart: {{{{ .Chart.Name }}}}-{{{{ .Chart.Version }}}}
{{{{- include "{safe_name}.selectorLabels" . | nindent 0 }}}}
app.kubernetes.io/version: {{{{ .Chart.AppVersion | quote }}}}
app.kubernetes.io/managed-by: {{{{ .Release.Service }}}}
{{{{- end }}}}

{{{{- define "{safe_name}.selectorLabels" -}}}}
app.kubernetes.io/name: {{{{ .Chart.Name }}}}
app.kubernetes.io/instance: {{{{ .Release.Name }}}}
{{{{- end }}}}
"""

    return [
        GeneratedFile(f"helm/{safe_name}/Chart.yaml",              chart_yaml),
        GeneratedFile(f"helm/{safe_name}/values.yaml",             values_yaml),
        GeneratedFile(f"helm/{safe_name}/templates/deployment.yaml", deployment_yaml),
        GeneratedFile(f"helm/{safe_name}/templates/service.yaml",  service_yaml),
        GeneratedFile(f"helm/{safe_name}/templates/_helpers.tpl",  helpers_tpl),
    ]


# ── ArgoCD Application manifest ────────────────────────────────────────────────

def generate_argocd_manifest(
    app_name: str,
    repo_url: str,
    helm_path: str,
    namespace: str,
    cluster_server: str = "https://kubernetes.default.svc",
    project: str = "default",
) -> GeneratedFile:
    content = f"""# Auto-generated by UniOps Deployment Engine
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {app_name}
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: uniops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {project}
  source:
    repoURL: {repo_url}
    targetRevision: main
    path: {helm_path}
    helm:
      releaseName: {app_name}
  destination:
    server: {cluster_server}
    namespace: {namespace}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
"""
    return GeneratedFile(f"gitops/{app_name}-application.yaml", content)
