# AUTO-GENERATED by start-app-infra.sh — do not edit by hand.
# App-layer state is stored under a separate key in the bootstrap-owned bucket.
terraform {
  backend "s3" {
    bucket         = "uniops-terraform-state"
    key            = "app/terraform.tfstate"
    region         = "us-east-2"
    dynamodb_table = "uniops-terraform-locks"
    encrypt        = true
  }
}
