environment: prod

frontend:
  image: "663476173962.dkr.ecr.us-east-2.amazonaws.com/uniops-frontend:174c371486284f7e3767e1b70847629647b2a9ec-57"
  replicas: 3
  port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

backend:
  image: "663476173962.dkr.ecr.us-east-2.amazonaws.com/uniops-backend:174c371486284f7e3767e1b70847629647b2a9ec-57"
  replicas: 1
  port: 8000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  efsId: "fs-87654321"
  logBucket: "uniops-logs-prod"
  backupBucket: "uniops-backups-prod"

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: uniops-alb-prod
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
          serviceName: frontend
          servicePort: 80
        - path: /api
          pathType: Prefix
          serviceName: backend
          servicePort: 8000

serviceAccount:
  create: true
  name: "uniops-sa"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::663476173962:role/uniops-irsa-role-prod"
