---
# Handlers for jenkins-tools role

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: yes

- name: User Group Changed
  ansible.builtin.debug:
    msg: "User has been added to a new group (e.g., docker). Please re-log or reboot for changes to take effect."

- name: Git Config Changed
  ansible.builtin.debug:
    msg: "Git global configuration has been updated."
