---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: uniops-celery-worker
  namespace: uniops
  labels:
    app.kubernetes.io/name: uniops
    app.kubernetes.io/component: celery-worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: uniops
      app.kubernetes.io/component: celery-worker