---
- name: Provision Jenkins Server for EKS Deployment
  hosts: jenkins_server
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - jenkins-tools

  post_tasks:
    - debug:
        msg: "Jenkins EKS toolchain has been successfully provisioned."