from __future__ import annotations
from typing import Any, Dict, List, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from app.services.investigation.filter.engine import FilterEngine
from app.services.investigation.search.engine import SearchEngine
from .planner import QueryPlanStep
from app.schemas.investigation import InvestigationResult
from app.utils.logger import logger
import time

class QueryExecutor:
    """
    The QueryExecutor runs the plan generated by the Planner and Optimizer.
    It orchestrates the low-level engines to produce a final result set.
    """

    def __init__(self, db_session: AsyncSession, filter_engine: FilterEngine, search_engine: SearchEngine):
        self.db = db_session
        self.filter_engine = filter_engine
        self.search_engine = search_engine

    async def execute(self, steps: List[QueryPlanStep], target_entity: str) -> InvestigationResult:
        """
        Executes the plan steps and returns a consolidated result.
        """
        start_time = time.time()
        final_results = []
        total_count = 0

        # For simplicity in this deterministic engine, we execute the most selective step
        # and treat it as the primary result set.
        if not steps:
            return InvestigationResult(
                results=[], total_count=0, page=1, page_size=50,
                total_pages=0, execution_time_ms=0.0
            )

        # Execute the top priority step
        primary_step = steps[0]

        if primary_step.engine_type == "search":
            logger.info(f"[QueryExecutor] Executing search step for {target_entity}")
            results = await self.search_engine.search(
                query=primary_step.params["query"],
                entity_types=[target_entity],
                limit=primary_step.params["limit"],
                offset=primary_step.params["offset"]
            )
            final_results = results
            total_count = len(results) # Simplification for mock/base impl

        elif primary_step.engine_type == "filter":
            logger.info(f"[QueryExecutor] Executing filter step for {target_entity}")
            # In a real impl, we'd resolve the model for target_entity
            # and use filter_engine.apply_filters()
            # For now, we simulate a filtered result set
            final_results = [{"id": "simulated-id", "type": target_entity, "status": "filtered"}]
            total_count = 1

        execution_time = (time.time() - start_time) * 1000

        return InvestigationResult(
            results=final_results,
            total_count=total_count,
            page=1, # Derived from params
            page_size=50,
            total_pages=1,
            execution_time_ms=execution_time
        )
