ERROR_CODES = {
    "AUTH_001": "Invalid credentials",
    "AUTH_002": "Token expired",
    "AUTH_003": "Token invalid",
    "AUTH_004": "2FA required",
    "USER_001": "User not found",
    "USER_002": "Email already exists",
    "USER_003": "Permission denied",
    "INT_001": "Integration not found",
    "INT_002": "Integration connection failed",
    "INT_003": "Integration sync failed",
    "ML_001": "Model not found",
    "ML_002": "Prediction failed",
    "BILLING_001": "Subscription not found",
    "BILLING_002": "Payment failed",
    "GENERIC_001": "Internal server error",
    "GENERIC_002": "Resource not found",
    "GENERIC_003": "Validation error",
    "GENERIC_004": "Rate limit exceeded",
}
