PERMISSIONS = {
    "users:read":                "View users",
    "users:write":               "Create/update users",
    "users:delete":              "Delete users",
    "integrations:read":         "View integrations",
    "integrations:write":        "Create/update integrations",
    "pipelines:read":            "View pipelines",
    "pipelines:write":           "Manage pipelines",
    "security:read":             "View security data",
    "security:write":            "Manage security findings",
    "security:scan":             "Trigger security scans",
    "security:resolve":          "Resolve/suppress threats",
    "security:policies:read":    "View security policies",
    "security:policies:write":   "Create/update security policies",
    "security:exceptions:read":  "View exception requests",
    "security:exceptions:write": "Create exception requests",
    "security:exceptions:approve":"Approve/reject exception requests",
    "security:reports:read":     "View security reports",
    "security:reports:generate": "Generate security reports",
    "compliance:read":           "View compliance data",
    "compliance:write":          "Manage compliance frameworks",
    "costs:read":                "View cost data",
    "costs:write":               "Manage cost settings",
    "ml:read":                   "View ML insights",
    "ml:write":                  "Manage ML models",
    "audit:read":                "View audit logs",
    "admin:all":                 "Full admin access",
}

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "super_admin": list(PERMISSIONS.keys()),
    "admin": [
        "users:read", "users:write", "users:delete",
        "integrations:read", "integrations:write",
        "security:read", "security:write", "security:scan", "security:resolve",
        "security:policies:read", "security:policies:write",
        "security:exceptions:read", "security:exceptions:write", "security:exceptions:approve",
        "security:reports:read", "security:reports:generate",
        "compliance:read", "compliance:write",
        "costs:read", "ml:read", "audit:read",
    ],
    "security_engineer": [
        "security:read", "security:write", "security:scan", "security:resolve",
        "security:policies:read", "security:policies:write",
        "security:exceptions:read", "security:exceptions:write", "security:exceptions:approve",
        "security:reports:read", "security:reports:generate",
        "compliance:read",
        "integrations:read", "users:read", "audit:read",
    ],
    "security_analyst": [
        "security:read",
        "security:policies:read",
        "security:exceptions:read", "security:exceptions:write",
        "security:reports:read",
        "compliance:read",
        "users:read",
    ],
    "devops_engineer": [
        "security:read", "security:scan",
        "security:policies:read",
        "security:reports:read",
        "integrations:read",
        "pipelines:read", "pipelines:write",
    ],
    "compliance_manager": [
        "compliance:read", "compliance:write",
        "security:read",
        "security:policies:read", "security:policies:write",
        "security:exceptions:read", "security:exceptions:approve",
        "security:reports:read", "security:reports:generate",
        "audit:read",
    ],
    "auditor": [
        "security:read",
        "security:policies:read",
        "security:exceptions:read",
        "security:reports:read",
        "compliance:read",
        "audit:read",
    ],
    "executive": [
        "security:read",
        "security:reports:read",
        "compliance:read",
        "costs:read",
        "ml:read",
    ],
    "cost_analyst": ["costs:read", "costs:write", "ml:read"],
    "developer":    ["security:read", "pipelines:read"],
    "viewer":       ["security:read"],
}
