PLANS = {
    "free": {
        "name": "Free",
        "price": 0,
        "seats": 3,
        "integrations": 2,
        "api_calls_per_month": 10_000,
        "features": ["command_center", "basic_devops"],
        "feature_list": [
            "3 team members",
            "2 integrations",
            "10k API calls/mo",
            "Command Center only",
            "Community support",
        ],
    },
    "starter": {
        "name": "Starter",
        "price": 49,
        "seats": 10,
        "integrations": 5,
        "api_calls_per_month": 100_000,
        "features": ["command_center", "devops", "security_basic", "cost_basic"],
        "feature_list": [
            "10 team members",
            "5 integrations",
            "100k API calls/mo",
            "DevOps + Security + Cost dashboards",
            "Email support",
        ],
    },
    "professional": {
        "name": "Professional",
        "price": 149,
        "seats": 25,
        "integrations": 15,
        "api_calls_per_month": 500_000,
        "features": ["all"],
        "feature_list": [
            "25 team members",
            "15 integrations",
            "500k API calls/mo",
            "All dashboards + ML Insights",
            "SSO (SAML) + Priority support",
        ],
    },
    "enterprise": {
        "name": "Enterprise",
        "price": -1,
        "seats": -1,
        "integrations": -1,
        "api_calls_per_month": -1,
        "features": ["all", "sso", "audit", "sla"],
        "feature_list": [
            "Unlimited team members",
            "Unlimited integrations",
            "Unlimited API calls",
            "Custom SLA + SLO",
            "24/7 dedicated support",
        ],
    },
}
