apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uniops
resources:
  - ../../base
images:
  - name: uniops-backend
    newName: uniops-backend
    newTag: dev
  - name: uniops-frontend
    newName: uniops-frontend
    newTag: dev
configMapGenerator:
  - name: uniops-config
    behavior: merge
    literals:
      - APP_ENV=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - CORS_ORIGINS=["http://localhost:5173","http://localhost:3000","http://uniops.local"]
      - FRONTEND_URL=http://uniops.local
