apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uniops.fullname" . }}-config
  labels:
    {{- include "uniops.labels" . | nindent 4 }}
data:
  EFS_ID: {{ .Values.backend.efsId | quote }}
  LOG_BUCKET_NAME: {{ .Values.backend.logBucket | quote }}
  BACKUP_BUCKET_NAME: {{ .Values.backend.backupBucket | quote }}
