apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uniops.fullname" . }}-backend
  labels:
    {{- include "uniops.labels" . | nindent 4 }}
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "uniops.selectorLabels" . | nindent 6 }}
      app: backend
  template:
    metadata:
      labels:
        {{- include "uniops.selectorLabels" . | nindent 8 }}
        app: backend
    spec:
      serviceAccountName: {{ include "uniops.fullname" . }}-sa
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: uniops-db-secret
          env:
            - name: EFS_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "uniops.fullname" . }}-config
                  key: EFS_ID
            - name: LOG_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "uniops.fullname" . }}-config
                  key: LOG_BUCKET_NAME
            - name: BACKUP_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "uniops.fullname" . }}-config
                  key: BACKUP_BUCKET_NAME
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
