apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "uniops.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "uniops.selectorLabels" . | nindent 4 }}
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "uniops.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "uniops.selectorLabels" . | nindent 4 }}
    app: backend
